services:
  - type: web
    name: smart-education-ml-service
    env: docker
    plan: free
    dockerfilePath: ./ml-service/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
