services:
  - type: web
    name: smart-education-ml-service
    env: node
    region: oregon
    plan: free
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
